version: '3.8'
services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: snapp-postgres
    environment:
      - POSTGRES_USER=snapp
      - POSTGRES_PASSWORD=snapp_pass
      - POSTGRES_DB=snappdb
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    restart: always

  redis:
    image: redis:7
    container_name: snapp-redis
    ports:
      - '63799:6379'
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: snapp-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5673:5673'
      - '15673:15673'
    restart: always

  minio:
    image: minio/minio
    container_name: snapp-minio
    environment:
      - MINIO_ROOT_USER=guest
      - MINIO_ROOT_PASSWORD=guest
    ports:
      - '9000:9000'
      - '9001:9001'
    restart: always

volumes:
  pgdata:
